#include "../../../l/lib.h"

vector<string> Q = {
        "AC",
        "AG",
        "AL",
        "AM",
        "AR",
        "AS",
        "AT",
        "AU",
        "B",
        "BA",
        "BE",
        "BH",
        "BI",
        "BK",
        "BR",
        "C",
        "CA",
        "CD",
        "CE",
        "CF",
        "CL",
        "CM",
        "CN",
        "CO",
        "CR",
        "CS",
        "CU",
        "DB",
        "DS",
        "DY",
        "ER",
        "ES",
        "EU",
        "F",
        "FE",
        "FL",
        "FM",
        "FR",
        "GA",
        "GD",
        "GE",
        "H",
        "HE",
        "HF",
        "HG",
        "HO",
        "HS",
        "I",
        "IN",
        "IR",
        "K",
        "KR",
        "LA",
        "LI",
        "LR",
        "LU",
        "LV",
        "MC",
        "MD",
        "MG",
        "MN",
        "MO",
        "MT",
        "N",
        "NA",
        "NB",
        "ND",
        "NE",
        "NH",
        "NI",
        "NO",
        "NP",
        "O",
        "OG",
        "OS",
        "P",
        "PA",
        "PB",
        "PD",
        "PM",
        "PO",
        "PR",
        "PT",
        "PU",
        "RA",
        "RB",
        "RE",
        "RF",
        "RG",
        "RH",
        "RN",
        "RU",
        "S",
        "SB",
        "SC",
        "SE",
        "SG",
        "SI",
        "SM",
        "SN",
        "SR",
        "TA",
        "TB",
        "TC",
        "TE",
        "TH",
        "TI",
        "TL",
        "TM",
        "TS",
        "U",
        "V",
        "W",
        "XE",
        "Y",
        "YB",
        "ZN",
        "ZR"
};

class FElementary { public:void solve(istream& cin, ostream& cout) {
        string S; cin >> S;
        int N = S.size();
        vector<bool> D(N+1, false);
        D[0] = true;
        for (int i = 0; i < N; ++i) {
            if (!D[i]) continue;
            for (string q: Q) {
                if (S.substr(i, q.size()) == q) {
                    D[i+q.size()] = true;
                }
            }
        }
        if (D[N]) {
            cout << "YES\n";
        } else {
            cout << "NO\n";
        }
    }
};
